#!/bin/sh

# This is the error reporter I am using in my project, also made by me.
# This program was modified, I give credit to myself.

# This program is intended for use in 3rd party projects.
# This could be used for error reporting. Or finding system problems.

# Linux-System-Info v0.0.1

# Using this in your project will requrire you source this project


# This sources the program, just leave this here

echo "NOTICE: Error reporting, Source: GitHub.com/AppIns/Linux-System-Info";
echo "NOTICE: Some info will be recorded. All files can be found in ~/.DesktopCreator";

# Comment or uncomment anything bellow to change reporting info.

# Gather Kernal info
SystemKernName=$(uname -n);
SystemKernVers=$(uname -r);

# Hardware info, (Not default)
#SystemHardware=$(uname -m);

# Username (Not default)
#SystemName=$(uname -n);

# Version and time reporting
SystemTime=$(date);
ProgramVersion="v0.1.2 Revision 1";
ProgramName="Desktop-Creator";

# Find home directory.
cd ~;
homedir=$(pwd);

# Create directory for error reporting
# NOTE: Change the name of the directory BEFORE using
if [ -d "$homedir/.DesktopCreator" ]; then
  # If .DesktopCreator exists change directory
  cd .DesktopCreator
  if [ -d "$homedir/.DesktopCreator/Logs" ]; then
    # If 'Logs' exists change directory
    cd Logs
  else
    # If 'Logs' does not exist, this should not technically happen
    mkdir Logs
    cd Logs
  fi
else
  # If nothing exists create everything
  mkdir .DesktopCreator;
  mkdir .DesktopCreator/Logs;
  # And change directories
  cd ~/.DesktopCreator/Logs;
fi

# Time Vars
Sec=$(date +%s);
Day=$(date "+%m %d %y");

# New log file, this is where the magic happens
echo "-NEW REPORT AT $Sec-
Date: $SystemTime
Kernal: $SystemKernName $SystemKernVers
Program: $ProgramName $ProgramVersion
Command: $DCType $DCfilename
Terminal: True,
Type: Application,
Source: GitHub.com/AppIns/Desktop-Creator,
Name: $DCSaveName
This document was generated by GitHub.com/AppIns/Linux-System-Info
If problems are found, send this report to: AlexAndersonOne@gmail.com
Signed: AppIns, 10-11-15.
-END REPORT-


" >> "$Day.txt";
